Insert into H11_ANDERSEN.EIENDOMTYPE_TBL (TYPE_ID,TYPE_NAVN) values (1,'Leilighet');
Insert into H11_ANDERSEN.EIENDOMTYPE_TBL (TYPE_ID,TYPE_NAVN) values (2,'Rekkehus');
Insert into H11_ANDERSEN.EIENDOMTYPE_TBL (TYPE_ID,TYPE_NAVN) values (3,'Enebolig');
Insert into H11_ANDERSEN.EIENDOMTYPE_TBL (TYPE_ID,TYPE_NAVN) values (4,'Gård');
Insert into H11_ANDERSEN.EIENDOMTYPE_TBL (TYPE_ID,TYPE_NAVN) values (5,'Diverse');